# Generated by Django 3.2.5 on 2021-07-06 07:42

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(max_length=10)),
                ('name', models.CharField(default='', max_length=200)),
                ('age', models.IntegerField(default=0)),
                ('mobile', models.CharField(default='', max_length=20)),
                ('email', models.CharField(default='', max_length=500)),
                ('country_code', models.CharField(default='+91', max_length=10)),
                ('status', models.IntegerField(default=1)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
            ],
        ),
    ]
