# Generated by Django 3.2.5 on 2021-07-11 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='analysisreport',
            name='num_of_infringements',
        ),
        migrations.AddField(
            model_name='cctvcam',
            name='area',
            field=models.DecimalField(decimal_places=6, default=1, max_digits=9),
        ),
        migrations.AddField(
            model_name='organization',
            name='logo',
            field=models.ImageField(default=None, upload_to=''),
        ),
        migrations.AddField(
            model_name='organization',
            name='map',
            field=models.ImageField(default=None, upload_to=''),
        ),
        migrations.AddField(
            model_name='zone',
            name='logo',
            field=models.ImageField(default=None, upload_to=''),
        ),
    ]
