# Generated by Django 3.2.3 on 2021-07-10 05:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysisreport',
            name='total_people',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='analysisreport',
            name='zone',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='client.zone'),
        ),
    ]
