# Generated by Django 3.2.5 on 2021-07-10 14:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0002_auto_20210710_1112'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysisreport',
            name='camera',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='client.cctvcam'),
        ),
    ]
