# Generated by Django 3.2.3 on 2021-07-10 19:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0004_auto_20210710_2354'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AnalysisReport',
        ),
    ]
